### ISSUE TITLE
Cannot find module 'pg'

### ISSUE THREAD

**Issue by 8000meters** [djs42012/boiler-plate#1]
Hello!

I am a fellow CodeSmith student and trying to utilize your amazing template here to build a full-stack app however I am getting the 'Cannot find module 'pg'' error. I tried npm install pg, however that resulted in another string of errors including "./internal/streams/BufferList". Running npm install also resulted in that same error.

M1 Macbook Pro
Node 16.15.1

![Screen Shot 2022-07-24 at 12 37 08 PM](https://user-images.githubusercontent.com/105823811/180661226-217f982d-10da-4df5-a89e-aa89f82dd8e3.png)
![Screen Shot 2022-07-24 at 12 36 52 PM](https://user-images.githubusercontent.com/105823811/180661229-0e08aa3b-ee05-4602-870a-c370d48bfdd6.png)
![Screen Shot 2022-07-24 at 12 36 32 PM](https://user-images.githubusercontent.com/105823811/180661230-f87e7daf-3fdd-41f9-b001-ac02a61bd7be.png)
.

**Comment by djs42012** [comment]
Hey there,
Unfortunately I was not able to reproduce this issue doing a fresh `git-clone` of the repo followed by `npm-install`. I'm using node 16.14.2 on Ubuntu. You might check [this](https://stackoverflow.com/a/67778126) post to see if your version of `node-sass` needs updating. Here's [another](https://sebhastian.com/npm-err-code-1/) more general post about `npm ERR: code 1`, which ironically also addresses an issue with `node-sass`. Looks like a common problem. Good luck, and keep me posted (also, if you could either edit your first comment or reply separately with your node version and operating system, that would be great as well).

**Comment by 8000meters** [comment]
Turns out it was an issue with node-sass. Its is unclear what exactly was wrong since the node versions and sass version were correctly updated. However I was able to resolve it by following [this](https://stackoverflow.com/questions/58623072/npm-node-sass-installation-fails) solution and just changing the dependency in the json. Thank you for pointing me in the right direction!
